### ISSUE TITLE
Android error

### ISSUE THREAD

**Issue by anhtuank7c** [virusvn/react-native-svg-animated-linear-gradient#1]
Hi,
I tried to use on Pure React Native with `react-native-svg`.
Weird issue on android, `Stop` offset cannot be filled by `this.state.offsets[index]`.
It will throw error
![screen shot 2017-06-24 at 12 19 57 pm](https://user-images.githubusercontent.com/3163410/27505951-7b0d165c-58d7-11e7-817c-5790aa155189.png)
If i fill as fixed value like `offset="0"` it will run properly.

**Comment by virusvn** [comment]
I reported this bug to react-native-svg team on this issue (https://github.com/react-native-community/react-native-svg/issues/385).
Current, it's known bug, I will update the component when that issue was fixed.

**Comment by virusvn** [comment]
Fixed

**Comment by rezasamsu** [comment]
but i still have that problem on android even thought offset value has already different

**Comment by mrdezzods** [comment]
+1 still the same issue. Is anyone working on it?
